#!/usr/bin/env python3
"""Write PROGRESS.md from objdiff's report.

Run inside the build container after a successful build:

    tools/dock python3 tools/progress.py

objdiff-cli compares every unit in objdiff.json (written by configure.py) and reports, per progress category,
how much code is matched: compiled from C/C++ into exactly the original bytes. Assembly-only units count toward
the totals but never as matched.
"""

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPORT = Path("build/report.json")
OUT = Path("PROGRESS.md")


def pct(part: int, whole: int) -> str:
    return f"{100 * part / whole:.2f}%" if whole else "-"


def row(name: str, m: dict) -> str:
    code, total = int(m.get("matched_code", 0)), int(m.get("total_code", 0))
    funcs, nfuncs = m.get("matched_functions", 0), m.get("total_functions", 0)
    return f"| {name} | {funcs:,} / {nfuncs:,} | {pct(funcs, nfuncs)} | {code:,} / {total:,} | {pct(code, total)} |"


def main() -> None:
    r = subprocess.run(["objdiff-cli", "report", "generate", "-p", ".", "-o", str(REPORT)], cwd=ROOT,
                       capture_output=True, text=True)
    if r.returncode:
        sys.exit(f"objdiff-cli failed:\n{r.stderr}")
    report = json.loads((ROOT / REPORT).read_text())
    config = json.loads((ROOT / "objdiff.json").read_text())
    names = {c["id"]: c["name"] for c in config["progress_categories"]}

    lines = [
        "# Progress",
        "",
        "Generated by `tools/progress.py` from objdiff's report; do not edit by hand. A function counts as matched",
        "when its C/C++ compiles to exactly the original bytes; the build links it once its whole unit matches.",
        "",
        "| Category | Functions | | Code bytes | |",
        "|---|---|---|---|---|",
    ]
    for cat in report["categories"]:
        lines.append(row(names.get(cat["id"], cat["id"]), cat["measures"]))
    lines.append(row("**All**", report["measures"]))
    lines += [
        "",
        "Categories follow the map in [docs/layout.md](docs/layout.md). Hand-written assembly and VU microcode are",
        "expected to stay assembly, as in the original source.",
        "",
    ]
    (ROOT / OUT).write_text("\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
