#!/usr/bin/env python3
"""Generate build.ninja for the Burnout 3 matching decomp.

Run inside the build container (tools/dock python3 configure.py), then `tools/dock ninja`.

Steps:
  1. orig/SLUS_210.50 (your copy, hash-checked) -> orig/SLUS_210.50.rom (raw load segment)
  2. splat splits the rom into asm/ and assets/ and writes the linker script into build/
  3. build.ninja assembles, links, objcopies the load segment and rebuilds the ELF container,
     failing unless the result has the original SHA-1
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BASENAME = "SLUS_210.50"
ORIG_ELF = Path("orig") / BASENAME
ORIG_ROM = Path("orig") / f"{BASENAME}.rom"
SPLAT_YAML = Path("splat/b3.yaml")
BUILD = Path("build")

CROSS = "mips-linux-gnu-"
AS_FLAGS = "-EL -march=r5900 -mabi=eabi -G 0 -no-pad-sections -I include"
LD_SCRIPTS = [
    BUILD / f"{BASENAME}.ld",
    BUILD / "undefined_syms_auto.txt",
    BUILD / "undefined_funcs_auto.txt",
    Path("config/linker_extra.ld"),
]


def run(cmd: list[str]) -> None:
    print("+", " ".join(cmd))
    subprocess.run(cmd, cwd=ROOT, check=True)


def write_ninja(asm_files: list[Path]) -> None:
    elf = BUILD / f"{BASENAME}.elf"
    rom = BUILD / f"{BASENAME}.rom"
    out = BUILD / BASENAME

    lines = [
        "# Generated by configure.py. Do not edit.",
        "ninja_required_version = 1.10",
        "",
        "rule as",
        f"  command = {CROSS}as {AS_FLAGS} -o $out $in",
        "  description = AS $in",
        "",
        "rule ld",
        f"  command = {CROSS}ld -EL {' '.join(f'-T {s}' for s in LD_SCRIPTS)} "
        f"-Map {BUILD}/{BASENAME}.map --no-check-sections -o $out",
        "  description = LD $out",
        "",
        "rule objcopy",
        f"  command = {CROSS}objcopy -O binary -j .main $in $out",
        "  description = OBJCOPY $out",
        "",
        "rule elf",
        "  command = python3 tools/elf.py rebuild $in $out --check",
        "  description = ELF $out",
        "",
    ]

    objs = []
    for s in asm_files:
        o = BUILD / s.with_suffix(".o")
        objs.append(o)
        lines.append(f"build {o}: as {s}")
    lines += [
        "",
        f"build {elf}: ld | {' '.join(str(o) for o in objs)} {' '.join(str(s) for s in LD_SCRIPTS)}",
        f"build {rom}: objcopy {elf}",
        f"build {out}: elf {rom}",
        "",
        f"default {out}",
        "",
    ]
    (ROOT / "build.ninja").write_text("\n".join(lines))


def write_objdiff(asm_files: list[Path]) -> None:
    """objdiff units: target objects come from splat asm. Base objects (from C) are added as
    translation units get decompiled."""
    units = []
    for s in asm_files:
        if s.parts[1] == "data":
            continue
        units.append({
            "name": s.with_suffix("").as_posix(),
            "target_path": (BUILD / s.with_suffix(".o")).as_posix(),
            "metadata": {"progress_categories": ["unsplit"]},
        })
    config = {
        "min_version": "2.0.0",
        "custom_make": "ninja",
        "build_target": False,
        "build_base": True,
        "watch_patterns": ["*.c", "*.cpp", "*.h", "*.hpp", "*.s", "*.inc"],
        "progress_categories": [
            {"id": "unsplit", "name": "Not yet split into translation units"},
            {"id": "game", "name": "Burnout 3 game code"},
            {"id": "rw", "name": "RenderWare 3.6"},
            {"id": "sce", "name": "Sony libsce"},
            {"id": "msl", "name": "Metrowerks runtime / MSL"},
        ],
        "units": units,
    }
    (ROOT / "objdiff.json").write_text(json.dumps(config, indent=2) + "\n")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--no-split", action="store_true", help="reuse existing asm/ instead of re-running splat")
    args = p.parse_args()

    if not (ROOT / ORIG_ELF).exists():
        sys.exit(f"missing {ORIG_ELF}: extract SLUS_210.50 from your disc first (see README.md)")
    if not (ROOT / ORIG_ROM).exists():
        run([sys.executable, "tools/elf.py", "extract", str(ORIG_ELF), str(ORIG_ROM)])

    if not args.no_split:
        run([sys.executable, "-m", "splat", "split", str(SPLAT_YAML)])

    asm_files = sorted(p.relative_to(ROOT) for p in (ROOT / "asm").rglob("*.s"))
    if not asm_files:
        sys.exit("no asm files found; run without --no-split")
    write_ninja(asm_files)
    write_objdiff(asm_files)
    print(f"wrote build.ninja and objdiff.json ({len(asm_files)} asm files)")


if __name__ == "__main__":
    main()
